locales:
  - en
  - et
source: ./source
build: ./build
assets: ./assets
assetsPath: /assets/
jade:
  basedir: ./source/_templates
  pretty: false
markdown:
  breaks: true
  html: false
stylus:
  pretty: false
port: 4000
